import type { Metadata } from "next";

import "./style.css";
import QueryProvider from "@/providers/QueryProvider";
import SessionProvider from "@/providers/SessionProvider";
import { Footer } from "@/widgets/Footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = ({ children } : LAYOUT_CHILD) => {

    return (
        <html lang="ko">
        <body className="min-h-full flex flex-col" suppressHydrationWarning>
            <SessionProvider>
                  <QueryProvider>
                    <div className="block w-[1000px] mx-auto pb-[120px]">
                        {children}
                    </div>
                    <Footer/>
                  </QueryProvider>
            </SessionProvider>
        </body>
        </html>
    )
}

export default RootLayout
