import type { Metadata } from "next";

import "./style.css";

import QueryProvider from "@/provider/QueryProvider";
import SessionProvider from "@/provider/SessionProvider";
import { Footer } from "@/widgets/Footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = ({ children }: LAYOUT_CHILD) => {
    return (
        <html lang="en" className={`h-full antialiased`}>
            <body cz-shortcut-listen="true" className="no-scrollbar">
                <SessionProvider>
                  <QueryProvider>
                    <div className="block w-[1000px] mx-[auto] pt-[20px] pb-[100px]">
                      {children}
                    </div>
                    <Footer/>
                    <div id="portal-root"></div>
                  </QueryProvider>
                </SessionProvider>
            </body>
        </html>
    );
};

export default RootLayout;
