import type { Metadata } from "next";

import "./style.css";
import QueryProvider from "@/providers/QueryProvider";
import SessionProvider from "@/providers/SessionProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = ({ children } : LAYOUT_CHILD) => {

    return (
        <html lang="ko">
        <body suppressHydrationWarning>
            <SessionProvider>
                  <QueryProvider>
                    {children}
                    <div id="portal-root"></div>
                  </QueryProvider>
            </SessionProvider>
        </body>
        </html>
    )
}

export default RootLayout
